### ISSUE TITLE
Installation failure : Error : 'las_convert_v2<-' is not an exported object from 'namespace:lastools

### ISSUE THREAD

**Issue by dcslagel** [Gitmaxwell/lastools#1]
Hi @Gitmaxwell,

I ran into the following error when attempting the README.md installation instructions:
**Error : 'las_convert_v2<-' is not an exported object from 'namespace:lastools'** 

My version of R is version.string R version 3.6.1 (2019-07-05).   Could someone else give it a try to verify whether the issue is only with my configuration or if others get the failure too?

Thanks,

DC

ps. Below is the full output from the install command. 

> devtools::install_github("Gitmaxwell/lastools")
Downloading GitHub repo Gitmaxwell/lastools@master
   checking for file ‘/private/var/folders/wg/0nrwp1vx2xs33kcghzhbdw6c0000gp/T/RtmpxGA9Rq/remotes395cb24dc2b/Gitmaxwell-lastools-b8cf4a5/DESCRIPTION
✔  checking for file ‘/private/var/folders/wg/0nrwp1vx2xs33kcghzhbdw6c0000gp/T/RtmpxGA9Rq/remotes395cb24dc2b/Gitmaxwell-lastools-b8cf4a5/DESCRIPTION
’
─  preparing ‘lastools’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘lastools_1.0.0.tar.gz’
   
* installing *source* package ‘lastools’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
**Error : 'las_convert_v2<-' is not an exported object from 'namespace:lastools'**
Error: unable to load R code in package ‘lastools’
Execution halted
ERROR: lazy loading failed for package ‘lastools’

**Comment by Gitmaxwell** [comment]
Please try again, versioning should be fine, there was a call inside one of the function documents which was not commented out. I just fixed and retested devtools::install_github("Gitmaxwell/lastools") and now works. Let me know if all good and will close

**Comment by dcslagel** [comment]
Hi @Gitmaxwell,

Yep, that solved the problem.  I successfully installed lastools and read a las file. This ticket can be closed now.

Thank you,

DC
